[CEERIINTERN_CREDENTIALS]
type = "service_account"
project_id = "ceeriintern"
private_key_id = "440751c7bf053828b027d497e5aa1c31bb4e9157"
private_key = -----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDm2sEUiWcwqJWj
VkXbspBHha2M+s/RXDMUu0IM/ryivmzoDJFh3DhsWLfNZsi3YgYz5cGp1SZJsjYd
ZklRDLIl5n9dHTmzWkb6ZWQ4RsKzvLzC8RoBz7ZbLumMTBJ4zE5+ynYnaFh5cDAW
2FzL/+XA/8m8rZA4agSM46wtjavAg4wiWhX5XASMYjlURHSdufCEAkqgIuUwA9NW
JUOSU2+8T3y+iadJkbugxCQmGzAFTpCIfX9VIsLUMfNDWsZccAK8HTlSWNZ8sfNC
d3RByowAX7WqUrIM3EEIV7fYz5jqgqFBd95phXtPpmX+7QBc7ynyyTaXfBhoiDF7
OXf1dNmZAgMBAAECggEADNEPUCsSug5aBG/5P+nJfdcLnByephJ22YtN7vfDlEt7
M2TjO2olDcrdJX+z3A6Kpp32Yw3s6sGEpJw1rNTGHTmPT6WcOvtjnmo7
